name: Oder Terminal Management
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build with Maven
        run: mvn --batch-mode package

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true

      - name: Generate javadoc
        run: mvn javadoc:javadoc

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'commit badge'
          add: '*.svg'

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: Upload Javadoc
        uses: actions/upload-artifact@v2
        with:
          name: javadoc
          path: target/site/apidocs/


      - name: Publish to SwaggerHub (if needed)
        run: |
          die() {
            echo -e "\e[0;31mERROR: $1 \e[0m"
            exit 1
          }
          update_new() {
            echo "Update new version"
            version=$(cat swagger.json|json "info.version")
            result=$(swaggerhub api:get MATHIEUKAMVITY/order-terminal-api/$version 2> /dev/null || echo "Not found")
            if [ "$result" == "Not found" ]
            then
              echo "Create a new version ${version}"
              swaggerhub api:create MATHIEUKAMVITY/order-terminal-api/$version -f swagger.json || die "Cannot create the version"
            else
              echo "Update the existing version ${version}"
              swaggerhub api:update MATHIEUKAMVITY/order-terminal-api/$version -f swagger.json || die "Cannot create the version"
            fi
            echo "Publish the version"
            swaggerhub api:publish MATHIEUKAMVITY/order-terminal-api/$version || die "Cannot publish the version"
          }
          npm i -g swaggerhub-cli
          npm install -g json-diff
          npm install -g json
          export SWAGGERHUB_API_KEY=${{ secrets.SWAGGERHUB_API_KEY }}
          [ -f swagger.json ] || die "swagger.json not found."
          swaggerhub api:get MATHIEUKAMVITY/order-terminal-api -j > published-swagger.json || die "Swagger hub has returned an error"
          json-diff published-swagger.json swagger.json && echo "Same version of OpenApi" || update_new

